name: mogi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2
  flutter_markdown: ^0.6.18
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  file_picker: ^6.2.0
  uuid: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  lazy_load_scrollview: ^1.3.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.20.2
  dart_openai: ^5.1.0
  provider: ^6.1.2
  animations: ^2.0.11
  supabase_flutter: ^2.3.4
  supabase: ^2.0.8
  xml: ^6.5.0
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  connectivity_plus: ^6.1.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  mockito: ^5.4.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
    - family: ShadowsIntoLight
      fonts:
        - asset: assets/fonts/ShadowsIntoLight-Regular.ttf 

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 21 